export const SEARCH_APPOINTMENTS = 'SEARCH APPOINTMENTS';
export const SEARCH_APPOINTMENTS_SUCCESSFUL = 'SEARCH APPOINTMENTS SUCCESSFUL';
export const SEARCH_APPOINTMENTS_FAILURE = 'SEARCH APPOINTMENTS FAILURE';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';