export const SEARCH_APPOINTMENTS = 'SEARCH APPOINTMENTS';
export const SEARCH_APPOINTMENTS_SUCCESSFUL = 'SEARCH APPOINTMENTS SUCCESSFUL';
export const SEARCH_APPOINTMENTS_FAILURE = 'SEARCH APPOINTMENTS FAILURE';